### ISSUE TITLE
Which Shell to be used for OS

### ISSUE THREAD

**Issue by xeon-zolt** [Bashmug/CLI-Interface#1]
their are so many shells avaliable 
like Bash , FIsh , Ksh , Tcsh , Zsh
now my question is which shell to use and why or make a custom shell ?

it is not at all related to interface but still a important question which shell should be used

**Comment by xeon-zolt** [comment]
http://hyperpolyglot.org/unix-shells
found this

**Comment by Sprinting** [comment]
This should not be an open issue, why not go with `bash` and `sh`, atm.

 Customisation can always take place later?

Edit; derped on closing. sorry 

Edit 2:
[Refer:](http://stackoverflow.com/a/5725402/5648997)
